name: Release Please

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  # Pre-release: chạy khi có push vào dev
  release-please-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-24.04
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GOPHER_TOKEN }}
          release-type: simple
          target-branch: dev
          prerelease: true
          prerelease-type: dev

  # Production release: chạy khi có push vào main
  release-please-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GOPHER_TOKEN }}
          release-type: simple
          target-branch: main
